id: P010673
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:19:17.658427
source_metadata:
  id: bdr:W1KG15977
  title: དབུ་མའི་སྤྱི་དོན་སྐལ་བཟང་མགུལ་རྒྱན་གྱི་དགོངས་དོན་གསལ་བར་བྱེད་པའི་ཡང་གསལ་སྒྲོན་མེ།
  author: ''
  volumes:
    d0c28a65bf8b4ad3bbb2b5935a7bf538:
      image_group_id: I1KG15986
      title: ''
      volume_number: 1
      total_pages: 332
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
