id: opecha:P010673
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG15977
  title: དབུ་མའི་སྤྱི་དོན་སྐལ་བཟང་མགུལ་རྒྱན་གྱི་དགོངས་དོན་གསལ་བར་བྱེད་པའི་ཡང་གསལ་སྒྲོན་མེ།
  volume: ''
  author: ''
