id: I8405717F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T05:20:44+00:00'
last_modified: '2022-06-08T16:42:41.265663+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG15977
  title: དབུ་མའི་སྤྱི་དོན་སྐལ་བཟང་མགུལ་རྒྱན་གྱི་དགོངས་དོན་གསལ་བར་བྱེད་པའི་ཡང་གསལ་སྒྲོན་མེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B7AC:
      image_group_id: I1KG15986
      title: ''
      total_pages: 332
      order: 1
      base_file: B7AC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
